server:
  servlet:
    context-path: /challenge

dna:
  mutant: AAAA,CCCC,TTTT,GGGG

spring:
    h2:
      console:
        enabled: true
        path: /h2-console
    datasource:
      url: jdbc:h2:mem:adndb
      username: sa
      password:
      driver-class-name: org.h2.Driver
      platform: h2

    jpa:
      properties:
        hibernate:
          show_sql: false

    cloud:
      appId: challenge-2021-meli